#include "pomp_lib.h"

struct ompregdescr omp_rd_307 = {
  "parallel", "", 0, "lu.c", 140, 140, 147, 147
};

#define POMP_DLIST_00307 shared(omp_rd_307,omp_rd_308)

struct ompregdescr omp_rd_308 = {
  "master", "", 0, "lu.c", 144, 144, 145, 145
};

struct ompregdescr omp_rd_309 = {
  "for", "", 0, "lu.c", 217, 217, 229, 229
};

struct ompregdescr omp_rd_310 = {
  "for", "", 0, "lu.c", 231, 231, 420, 420
};

struct ompregdescr omp_rd_311 = {
  "flush", "", 0, "lu.c", 237, 237, 0, 0
};

struct ompregdescr omp_rd_312 = {
  "flush", "", 0, "lu.c", 243, 243, 0, 0
};

struct ompregdescr omp_rd_313 = {
  "flush", "", 0, "lu.c", 418, 418, 0, 0
};

struct ompregdescr omp_rd_314 = {
  "for", "", 0, "lu.c", 455, 455, 467, 467
};

struct ompregdescr omp_rd_315 = {
  "for", "", 0, "lu.c", 469, 469, 660, 660
};

struct ompregdescr omp_rd_316 = {
  "flush", "", 0, "lu.c", 474, 474, 0, 0
};

struct ompregdescr omp_rd_317 = {
  "flush", "", 0, "lu.c", 480, 480, 0, 0
};

struct ompregdescr omp_rd_318 = {
  "flush", "", 0, "lu.c", 658, 658, 0, 0
};

struct ompregdescr omp_rd_319 = {
  "parallel", "", 0, "lu.c", 712, 712, 1165, 1165
};

#define POMP_DLIST_00319 shared(omp_rd_319,omp_rd_320,omp_rd_321,omp_rd_322,omp_rd_323,omp_rd_324,omp_rd_325,omp_rd_326)

struct ompregdescr omp_rd_320 = {
  "for", "", 0, "lu.c", 743, 743, 752, 752
};

struct ompregdescr omp_rd_321 = {
  "for", "", 0, "lu.c", 754, 754, 780, 780
};

struct ompregdescr omp_rd_322 = {
  "for", "", 0, "lu.c", 789, 789, 806, 806
};

struct ompregdescr omp_rd_323 = {
  "for", "", 0, "lu.c", 808, 808, 911, 911
};

struct ompregdescr omp_rd_324 = {
  "for", "", 0, "lu.c", 920, 920, 937, 937
};

struct ompregdescr omp_rd_325 = {
  "for", "", 0, "lu.c", 939, 939, 1044, 1044
};

struct ompregdescr omp_rd_326 = {
  "for", "", 0, "lu.c", 1049, 1049, 1164, 1164
};

struct ompregdescr omp_rd_327 = {
  "for", "", 0, "lu.c", 1269, 1269, 1611, 1611
};

struct ompregdescr omp_rd_328 = {
  "for", "", 0, "lu.c", 1637, 1637, 1984, 1984
};

struct ompregdescr omp_rd_329 = {
  "parallel", "", 0, "lu.c", 2000, 2000, 2045, 2045
};

#define POMP_DLIST_00329 shared(omp_rd_329,omp_rd_330,omp_rd_331,omp_rd_332,omp_rd_333,omp_rd_334)

struct ompregdescr omp_rd_330 = {
  "single", "", 0, "lu.c", 2013, 2013, 2016, 2016
};

struct ompregdescr omp_rd_331 = {
  "for", "", 0, "lu.c", 2018, 2018, 2029, 2029
};

struct ompregdescr omp_rd_332 = {
  "critical", "", 0, "lu.c", 2031, 2031, 2038, 2038
};

struct ompregdescr omp_rd_333 = {
  "barrier", "", 0, "lu.c", 2039, 2039, 0, 0
};

struct ompregdescr omp_rd_334 = {
  "single", "", 0, "lu.c", 2041, 2041, 2044, 2044
};

struct ompregdescr omp_rd_335 = {
  "parallel", "", 0, "lu.c", 2340, 2340, 2770, 2770
};

#define POMP_DLIST_00335 shared(omp_rd_335,omp_rd_336,omp_rd_337,omp_rd_338,omp_rd_339,omp_rd_340,omp_rd_341)

struct ompregdescr omp_rd_336 = {
  "for", "", 0, "lu.c", 2364, 2364, 2373, 2373
};

struct ompregdescr omp_rd_337 = {
  "for", "", 0, "lu.c", 2382, 2382, 2401, 2401
};

struct ompregdescr omp_rd_338 = {
  "for", "", 0, "lu.c", 2403, 2403, 2510, 2510
};

struct ompregdescr omp_rd_339 = {
  "for", "", 0, "lu.c", 2519, 2519, 2537, 2537
};

struct ompregdescr omp_rd_340 = {
  "for", "", 0, "lu.c", 2539, 2539, 2648, 2648
};

struct ompregdescr omp_rd_341 = {
  "for", "", 0, "lu.c", 2653, 2653, 2769, 2769
};

struct ompregdescr omp_rd_342 = {
  "parallel", "", 0, "lu.c", 2779, 2779, 2842, 2842
};

#define POMP_DLIST_00342 shared(omp_rd_342,omp_rd_343,omp_rd_344,omp_rd_345,omp_rd_346,omp_rd_347)

struct ompregdescr omp_rd_343 = {
  "for", "", 0, "lu.c", 2795, 2795, 2803, 2803
};

struct ompregdescr omp_rd_344 = {
  "for", "", 0, "lu.c", 2808, 2808, 2814, 2814
};

struct ompregdescr omp_rd_345 = {
  "for", "", 0, "lu.c", 2816, 2816, 2822, 2822
};

struct ompregdescr omp_rd_346 = {
  "for", "", 0, "lu.c", 2827, 2827, 2833, 2833
};

struct ompregdescr omp_rd_347 = {
  "for", "", 0, "lu.c", 2835, 2835, 2841, 2841
};

struct ompregdescr omp_rd_348 = {
  "parallel", "", 0, "lu.c", 2995, 2995, 3048, 3048
};

#define POMP_DLIST_00348 shared(omp_rd_348,omp_rd_349)

struct ompregdescr omp_rd_349 = {
  "for", "", 0, "lu.c", 3014, 3014, 3047, 3047
};

struct ompregdescr omp_rd_350 = {
  "parallel", "", 0, "lu.c", 3077, 3077, 3092, 3092
};

#define POMP_DLIST_00350 shared(omp_rd_350,omp_rd_351)

struct ompregdescr omp_rd_351 = {
  "for", "", 0, "lu.c", 3079, 3079, 3091, 3091
};

struct ompregdescr omp_rd_352 = {
  "master", "", 0, "lu.c", 3117, 3117, 3118, 3118
};

struct ompregdescr omp_rd_353 = {
  "parallel", "", 0, "lu.c", 3121, 3121, 3190, 3190
};

#define POMP_DLIST_00353 shared(omp_rd_353,omp_rd_354,omp_rd_355,omp_rd_356,omp_rd_357)

struct ompregdescr omp_rd_354 = {
  "for", "", 0, "lu.c", 3127, 3127, 3136, 3136
};

struct ompregdescr omp_rd_355 = {
  "barrier", "", 0, "lu.c", 3155, 3155, 0, 0
};

struct ompregdescr omp_rd_356 = {
  "barrier", "", 0, "lu.c", 3173, 3173, 0, 0
};

struct ompregdescr omp_rd_357 = {
  "for", "", 0, "lu.c", 3179, 3179, 3189, 3189
};

